###############################################
#                                             #
#       Google Home Automation Message        #
#                                             #
###############################################
- alias: Someone Arrived Home
  trigger:
    - platform: state
      entity_id:  device_tracker.7af57c88cdf9724e, device_tracker.3d3b9e82cde5b9c7 ,device_tracker.539571cb65c54121b0d0b38a1941c4ce, device_tracker.861678d45b62cbe7, device_tracker.2f276f4efc3d4e6f9cf2d5f078b3171c, device_tracker.334e6e718945401592bacc9c5ec625a5, device_tracker.9245f2e89c6243f892cd3210f56b4b54
      to: 'home'
  action:
      service: tts.google_say
      entity_id: 
        - media_player.living_room_speaker
        - media_player.basement_speaker
      data_template:
        message: >
           {% set person = trigger.from_state.attributes.friendly_name %}
           {%- macro greeting_sentence(person) -%}
           {{ [
           "Knock Knock! " ~ person + " just Arrived! We have missed you. Or at least myself And Alexa did." ~ person,
           "Guess who is home?" ~ person +" is!",
           person + " is now in the house.",
           "Our home is now complete! " ~ person + " is Home!",
           "Hey there! " ~ person + " is Home!",
           "Knock Knock. Guess who is home? "   ~ person +" is!",
           person ~ "! Is home!",
           "I know a secret! "  ~ person +" is home!"
           ] | random }}
           {%- endmacro -%}
           "{{greeting_sentence(person)}}"

- alias: Azaan Prayer Time
  trigger:
    - platform: state
      entity_id:  sensor.prayer
  action:
      service: tts.google_say
      entity_id: 
        - media_player.living_room_speaker
        - media_player.basement_speaker
      data_template:
        language: 'ar'
        message: >
            {% set next_pray = trigger.from_state.attributes['next pray'] %}
              {% if next_pray == 'fajr' %}
              {{'..حان الآن موعد صلاة الفَجر'}}

              {% elif next_pray == 'dhuhr' %}
              {{'..حان الآن موعد صلاة الظُّهر‎'}}

              {% elif next_pray == 'asr' %}
              {{'..حان الآن موعد صلاة العَصْرْ'}}

              {% elif next_pray == 'maghrib' %}
              {{'..حان الآن موعد صلاة المَغرِبْ'}}

              {% elif next_pray == 'isha' %}
              {{'..حان الآن موعد صلاة العِشَاءْ'}}

            {% endif %}




###############################################
#                                             #
#           Motion Light Automation           #
#                                             #
###############################################
- alias: Basement Stair Motion On
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.bs_motion
      to: 'active'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: switch.turn_on
      entity_id:
        - switch.bs_led_light

- alias: Basement Stair Motion Off
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.bs_motion

      # Optional
      to: 'inactive'
      # At least one of the following required

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: switch.turn_off
      entity_id:
        - switch.bs_led_light

- alias: Living Room Motion Inactive at Night
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.motion
      to: 'inactive'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'

      - condition: template
        value_template: '{{ states.light.lr_lamp_2.attributes.brightness == 20}}'
     
      - condition: template
        value_template: '{{ states.light.lr_lamp.attributes.brightness == 20}}'

  action:
      service: homeassistant.turn_off
      entity_id:
        - group.living_room

- alias: Living Room Motion Active at Night
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.motion
      to: 'active'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: template
        value_template: "{{ states('light.lr_lamp_2') == 'off'}}"
      - condition: template
        value_template: "{{ states('light.lr_lamp') == 'off'}}"
  action:
  - service: scene.turn_on
    entity_id:
      - scene.living_room_low_motion
  

###############################################
#                                             #
#      Slack: Slack Automated Message/Bot     #
#                                             #
###############################################

- alias: Someone Location Change
  trigger:
    - platform: state
      entity_id:  device_tracker.7af57c88cdf9724e, device_tracker.3d3b9e82cde5b9c7 ,device_tracker.539571cb65c54121b0d0b38a1941c4ce, device_tracker.861678d45b62cbe7, device_tracker.2f276f4efc3d4e6f9cf2d5f078b3171c, device_tracker.334e6e718945401592bacc9c5ec625a5, device_tracker.9245f2e89c6243f892cd3210f56b4b54
  action:
      service: notify.myslack
      data_template:
        message: >
            {% set entity_name = trigger.entity_id %}
            {% set current_state = states(entity_name) %}
            {% if states(entity_name) != 'not_home' %}
            {{trigger.from_state.attributes.friendly_name}} just arrived at {{ states(entity_name) }}
              {% if current_state == 'home' %}
              {{' :house:'}}
              {% elif current_state == 'gym' %}
              {{' :weight_lifter:'}}
              {% elif current_state == 'work' %}
              {{' :office:'}}
              {% elif current_state == 'capitalone' %}
              {{' :bank:'}}
              {% endif %}  
            {% else %}
            {{trigger.from_state.attributes.friendly_name}} did left {{trigger.from_state.state}}
            {% endif %}

###############################################
#                                             #
#         Scripts Automation Schedule         #
#                                             #
###############################################

# - alias: Check USCIS Status
#   trigger:
#     - platform: state
#       entity_id:  sensor.uscis_mohamad
#   action:
#   - service: shell_command.uscis_mohamad

###############################################
#                                             #
#           USCIS New Status Change           #
#                                             #
###############################################

- alias: Check USCIS Status
  trigger:
    - platform: state
      entity_id:  sensor.uscis_mohamad
  action:
      service: notify.important_channel
      data_template:
        message: ":statue_of_liberty: Status on {{trigger.from_state.attributes.friendly_name}} has been Change to {{states(trigger.entity_id)}}" 